[EDIT] workflow / [FIX] compilation

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -28,3 +28,20 @@ jobs: # étape qu'il fera
                     exit 1
                 fi
                 exit 0
+
+    compile:
+      runs-on: ubuntu-latest
+      steps:
+          - name: Checkout GH repo
+            uses: actions/checkout@master # init version
+          - name: Compile repository
+            run: make
+
+          - name: Check binary presence # -f check un fichier swap... sinon echo file error
+            run: |
+              if [ ! -f ./swapupcase ]; then
+                  echo "::error file=swapupcase,
+                  title=Binary Error::Binary not found"
+                  exit 1
+              fi
+              exit 0
